### ISSUE TITLE
Getting error: One of the packages require Grav >=1.6.0-beta.6. 

### ISSUE THREAD

**Issue by nawazm92** [getgrav/grav-plugin-database#1]
I installed fresh copy of grav using command
```composer create-project getgrav/grav ```

Here I need to install database plugin for which I'm using command like:
``` bin/gpm install database ```
there I get error 
```One of the packages require Grav >=1.6.0-beta.6. Please update Grav to the latest release.```

How can I fix that?

**Comment by w00fz** [comment]
The plugin requires Grav beta at the moment. You can install Grav beta by switching GPM to the testing channel.
